### PR TITLE
Fix emscripten compilation

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Review by frranck — COMMENTED** [review]
you're impacting all versions here, 
why not putting it with similar stuff line 66?

**Comment by phcoder** [comment]
It was on line 66 but then you discovered that if you put it there, the SDL build fails

**Comment by frranck** [comment]
there's two SDL versions 1 and 2.
maybe put it after ifeq ($(LIBSDL),)  so it doesn't impact SDL 1 ?

**Comment by frranck** [comment]
line 48?

**Comment by phcoder** [comment]
> line 48?

done

**Pull request merged**
