### PR TITLE
Remove SDL dependency and use new wav loader routines in libretro-common

### PR DESCRIPTION
**Pull request by bparker06**

### CODE REVIEW

**Comment by frranck** [comment]
Thanks, it is now mostly working, but there is an issue to have two sounds at the same time. seems the new sample cancels the previous one. you can hear it at the end of a level when everything explodes...

**Comment by twinaphex** [comment]
@aliaspider has a diff patch for that.

**Comment by aliaspider** [comment]
here is the diff:
```
--- common.c
+++ common.c
@@ -213,6 +213,7 @@ void play_fx() {
     }
 }
 
+#define CLAMP_I16(x) (x > INT16_MAX ? INT16_MAX : x < INT16_MIN ? INT16_MIN : x)
 void audio_callback(void)
 {
    if (!audio_batch_cb)
@@ -235,8 +236,8 @@ void audio_callback(void)
              unsigned chunk_size = num_frames * 2;
              unsigned sample = frames_left[i] * 2;
 
-             frame_sample_buf[j * 2] = samples[chunk_size - sample];
-             frame_sample_buf[(j * 2) + 1] = samples[(chunk_size - sample) + 1];
+             frame_sample_buf[j * 2] = CLAMP_I16(frame_sample_buf[j * 2] + samples[chunk_size - sample]);
+             frame_sample_buf[(j * 2) + 1] = CLAMP_I16(frame_sample_buf[(j * 2) + 1] + samples[(chunk_size - sample) + 1]);
              frames_left[i]--;
          }
      }
```

**Comment by frranck** [comment]
@bparker06 It seems to be failing on big endian:

< cant load /tmp/mrboom/0.WAV
< cant load /tmp/mrboom/1.WAV
< cant load /tmp/mrboom/2.WAV
< cant load /tmp/mrboom/3.WAV
< cant load /tmp/mrboom/4.WAV
< cant load /tmp/mrboom/5.WAV
< cant load /tmp/mrboom/6.WAV
< cant load /tmp/mrboom/7.WAV
< cant load /tmp/mrboom/8.WAV
< cant load /tmp/mrboom/9.WAV
< cant load /tmp/mrboom/10.WAV
< cant load /tmp/mrboom/11.WAV
< cant load /tmp/mrboom/12.WAV
< cant load /tmp/mrboom/13.WAV
< cant load /tmp/mrboom/14.WAV
< cant load /tmp/mrboom/15.WAV

**Comment by twinaphex** [comment]
Yeah, I think @leiradel mentioned back in the day that the rwav code had not been tested yet for big-endian compatibility. So you'll have to do something about that.

**Comment by aliaspider** [comment]
it does load the sound samples correctly on the wiiu. maybe the problem wasn't endianess related. what cpu did you test this on ? the wiiu uses a 32bit big endian ppc.

**Comment by twinaphex** [comment]
Let me test if it compiles for MacOS X PowerPC, and most importantly, if it runs.

**Comment by frranck** [comment]
@bparker06 Is there a way to get the sound to be less loud ?

**Comment by bparker06** [comment]
@frranck Sure. On these two lines:

https://github.com/libretro/mrboom-libretro/blob/master/common.c#L433 and 434

You would just multiply the CLAMP_I16 () value by any number between 0.0 and 1.0. So for example to make the volume 80% of what it is now, you multiply by 0.8.

**Comment by frranck** [comment]
@bparker06 thanks

**Pull request merged**
